### ISSUE TITLE
挂起线程失败，但仍然会有去获取堆栈的可能，此时可能就会出现其他BUG？

### ISSUE THREAD

**Issue by lbybug** [Knight-ZXW/Sliver#4]
![image](https://github.com/Knight-ZXW/Sliver/assets/28444406/7ffd466a-2b07-4fa9-b9f7-64005a433d00)

这里是将SuspendThreadByPeer改成了SuspendThreadByThreadId，目的是防止FATAL日志导致的crash，能理解

假设目标线程挂起失败输出了warn日志，但抓栈行为继续，则可能会出现很多奇怪的问题？

**Comment by Knight-ZXW** [comment]
确实，这里应该加下返回值的判断，从源码上看 suspend成功时会返回Thread* ， 失败时（比如线程已销毁）会返回null

**Comment by lbybug** [comment]
嗯，从源码看的确判断返回值可以解决该问题
![image](https://github.com/Knight-ZXW/Sliver/assets/28444406/5aba4dfb-07dd-4711-9b9a-9435caaefaf4)
